module.exports = [
  "About",
  "Animals farmed",
  "Art and design",
  "Australia news",
  "Better Business",
  "Books",
  "Business",
  "Business to business",
  "Cardiff",
  "Children's books",
  "Cities",
  "Opinion",
  "Community",
  "Crosswords",
  "Culture",
  "Culture Network",
  "Culture professionals network",
  "Edinburgh",
  "Education",
  "Guardian Enterprise Network",
  "Environment",
  "Extra",
  "Fashion",
  "Film",
  "Food",
  "Football",
  "Games",
  "Global development",
  "Global Development Professionals Network",
  "Guardian Government Computing",
  "Guardian Foundation",
  "Guardian Professional",
  "Healthcare Professionals Network",
  "Help",
  "Higher Education Network",
  "Housing Network",
  "Inequality",
  "Info",
  "Jobs",
  "Katine",
  "Law",
  "Leeds",
  "Life and style",
  "Local",
  "Local Leaders Network",
  "Media",
  "Media Network",
  "Membership",
  "Money",
  "Music",
  "News",
  "Politics",
  "Public Leaders Network",
  "Science",
  "Search",
  "Guardian Small Business Network",
  "Social Care Network",
  "Social Enterprise Network",
  "Society",
  "Society Professionals",
  "Sport",
  "Stage",
  "Teacher Network",
  "Technology",
  "From the Guardian",
  "From the Observer",
  "Travel",
  "Guardian holiday offers",
  "Television & radio",
  "UK news",
  "US news",
  "Wellness (Do NOT use)",
  "Voluntary Sector Network",
  "Weather",
  "Wellness",
  "Women in Leadership",
  "Working in development",
  "World news"
];
